repos:
  - repo: local
    hooks:
      - id: cargo-fmt
        name: "Cargo Format"
        entry: cargo fmt --all
        language: system
        pass_filenames: false
        types: [rust]

      - id: cargo-fix
        name: "Cargo Fix"
        entry: cargo fix --allow-dirty --allow-staged
        language: system
        pass_filenames: false
        types: [rust]

      - id: cargo-clippy
        name: "Cargo Clippy Lint"
        entry: cargo clippy --all-targets --all-features -- -D warnings
        language: system
        pass_filenames: false
        types: [rust]

      - id: cargo-test
        name: "Cargo Test"
        entry: cargo test --all
        language: system
        pass_filenames: false
        types: [rust]
