[package]
name = "hello_world"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["full"] }
axum = "0.8.3"
anyhow = "1.0"
clap = { version = "4", features = ["derive"] } # Add clap with the "derive" feature
serde_json = "1.0.140"
deepseek-api = "0.1.0-alpha.3"