version: '3.4'

services:

  postgres:
    image: ankane/pgvector:latest # pgvector preinstalled!
    container_name: postgres_vector
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rust_rag
    ports:
      - "5432:5432"
    restart: unless-stopped
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: postgres://postgres:password@postgres/rust_rag
    command: [ "./api" ]

  ollama:
    container_name: ollama
    image: ollama/ollama
    volumes:
      - ollama_data:/root/.ollama
    ports:
      - "11434:11434"

volumes:
  pgdata:
  ollama_data: